# Generated by Django 4.1.7 on 2023-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailintegration',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mailintegration',
            name='profileName',
            field=models.CharField(max_length=100),
        ),
    ]
